### ISSUE TITLE
Termination of the current application

### ISSUE THREAD

**Issue by thomasjuul** [dfds/dafda#22] opened 2021-01-28 23:17 UTC
https://github.com/dfds/dafda/blob/107df94f6cf70385a32e988806c9334c415b9e08/src/Dafda/Consuming/ConsumerHostedService.cs#L45

What is the argument for terminating the entire hosting application?
Why not just throw an exception here?

**Comment by martinosk** [comment] 2021-02-02 08:24
I believe this is a duplicate of #1
Current error handling in Dafda is extremely basic and relies on you hosting Dafda in a self-repairing environment such as K8s. 
There's room for improvement though.

**Closed by martinosk** 2021-02-02 08:24 UTC

**Comment by martinosk** [comment] 2021-02-02 08:26
Duplicate of #1
